{{- if .Values.prometheus.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-prometheus-stack.prometheus.serviceAccountName" . }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-prometheus
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-delete
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-hook
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-hook
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-delete
    helm.sh/hook-weight: "-4"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
rules:
# The following namespaces and configmaps permissions are needed to
# grab the kube-system namespace uid and write it out to a configmap.
- apiGroups: [""]
  resources:
  - namespaces
  verbs: ["get"]
- apiGroups: [""]
  resources:
  - configmaps
  verbs: ["get", "create", "patch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ template "kube-prometheus-stack.fullname" . }}-hook
  labels:
    app: {{ template "kube-prometheus-stack.name" . }}-hook
{{ include "kube-prometheus-stack.labels" . | indent 4 }}
  annotations:
    helm.sh/hook: pre-install,pre-delete
    helm.sh/hook-weight: "-3"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "kube-prometheus-stack.fullname" . }}-hook
subjects:
  - kind: ServiceAccount
    name: {{ template "kube-prometheus-stack.prometheus.serviceAccountName" . }}
    namespace: {{ $.Release.Namespace }}
---
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ .Release.Name }}-{{ .Values.mesosphereResources.hooks.prometheus.jobName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-install
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: {{ .Release.Name }}-{{ .Values.mesosphereResources.hooks.prometheus.jobName }}
    spec:
      serviceAccountName: {{ template "kube-prometheus-stack.prometheus.serviceAccountName" . }}
      containers:
        - name: kubectl
          image: {{ .Values.mesosphereResources.hooks.prometheus.kubectlImage | quote }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - kubectl create configmap {{ .Values.mesosphereResources.hooks.prometheus.configmapName }} -n {{ .Release.Namespace }} -oyaml --dry-run --save-config --from-literal=CLUSTER_ID=$(kubectl get namespace kube-system -o jsonpath="{.metadata.uid}") | kubectl apply -f -
      restartPolicy: OnFailure
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cleanup-{{ .Release.Name }}-{{ .Values.mesosphereResources.hooks.prometheus.configmapName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    helm.sh/hook: pre-delete
    helm.sh/hook-weight: "3"
    helm.sh/hook-delete-policy: hook-succeeded,before-hook-creation
spec:
  template:
    metadata:
      name: cleanup-{{ .Release.Name }}-{{ .Values.mesosphereResources.hooks.prometheus.configmapName }}
    spec:
      serviceAccountName: {{ template "kube-prometheus-stack.prometheus.serviceAccountName" . }}
      containers:
        - name: kubectl
          image: {{ .Values.mesosphereResources.hooks.prometheus.kubectlImage | quote }}
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - kubectl delete --ignore-not-found=true configmap {{ .Values.mesosphereResources.hooks.prometheus.configmapName }} -n {{ .Release.Namespace }}
      restartPolicy: OnFailure
{{- end }}
