apiVersion: v2
name: github
version: 0.2.0
description: "Registers for events of the specified types on the specified GitHub organization/repository. Brings those events into Knative."
sources:
- https://github.com/knative/eventing-contrib
maintainers:
- name: chhsia0
- name: gilbert88
appVersion: "v0.14.1"
