apiVersion: v1
name: github
version: 0.1.0
description: "Registers for events of the specified types on the specified GitHub organization/repository. Brings those events into Knative."
sources:
- https://github.com/knative/eventing-contrib
maintainers:
- name: Chun-Hung Hsiao
  email: chhsiao@mesosphere.io
appVersion: "v0.7.1"
