# This test ensures we can create an issuer, a certificate and a clusterissuer

issuers:
  - name: my-issuer
    namespace: kube-system
    secretName: my-issuer-ca

certificates:
  - name: my-certificate
    namespace: kube-system
    # where to store this certificate
    secretName: my-certificate-secret
    issuerRef:
      name: my-issuer
      kind: Issuer
    # These are the default usages for reference
    usages:
      - "digital signature"
      - "key encipherment"
    commonName: cert-manager
    duration: 87600h
    dnsNames:
      - example.com
      - www.example.com
    ipAddresses:
      - 127.0.0.1
    keyAlgorithm: rsa
    keyEncoding: pkcs8
    keySize: 4096
    # array of strings
    organization:
      - D2iQ, Inc.
      - Mesosphere, Inc.
    renewBefore: 360h

clusterissuers:
  - name: my-ca
    spec:
      ca:
        secretName: my-certificate-secret
