{{- if .Values.portalRBAC.kommanderUserInterface.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opsportal-kommander-admin
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
rules:
- nonResourceURLs:
  - {{ index .Values "kommander-ui" "ingress" "path" | trimSuffix "/" }}
  - {{ index .Values "kommander-ui" "ingress" "path" | trimSuffix "/" }}/*
  verbs:
  - "*"
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opsportal-kommander-view
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
rules:
- nonResourceURLs:
  - {{ index .Values "kommander-ui" "ingress" "path" | trimSuffix "/" }}
  - {{ index .Values "kommander-ui" "ingress" "path" | trimSuffix "/" }}/*
  verbs:
  - get
  - head
- nonResourceURLs:
  - /ops/portal/kommander/ui/graphql
  - {{ index .Values "kommander-ui" "ingress" "graphqlPath" | trimSuffix "/" }}
  verbs:
  - get
  - head
  - post
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opsportal-kommander-edit
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
rules:
- nonResourceURLs:
  - {{ index .Values "kommander-ui" "ingress" "path" | trimSuffix "/" }}
  - {{ index .Values "kommander-ui" "ingress" "path" | trimSuffix "/" }}/*
  verbs:
  - get
  - head
  - post
  - put
  - patch
{{- end}}
