apiVersion: v1
name: nvidia-driver
home: https://github.com/mesosphere/charts
appVersion: "1.0"
description: Nvidia Driver for konvoy
version: 0.1.6
maintainers:
  - name: joejulian
  - name: jongiddy
  - name: tillt
