apiVersion: v1
name: nvidia-device-plugin
home: https://github.com/mesosphere/charts
appVersion: "1.0"
description: Nvidia Device Plugin for konvoy
version: 0.1.3
maintainers:
  - name: jongiddy
  - name: tillt
