apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-mesh-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    monitoring: istio-mesh
    release: prometheus-kubeaddons
spec:
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [mixer]}
  namespaceSelector:
    any: true
  endpoints:
  - port: prometheus
    interval: {{ .Values.prometheus.scrapeInterval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: istio-component-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    monitoring: istio-components
    release: prometheus-kubeaddons
spec:
  selector:
    matchExpressions:
      - {key: istio, operator: In, values: [mixer,pilot,galley,citadel]}
  namespaceSelector:
    any: true
  endpoints:
  - port: http-monitoring
    interval: {{ .Values.prometheus.scrapeInterval }}
  - port: http-policy-monitoring
    interval: {{ .Values.prometheus.scrapeInterval }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: envoy-stats-monitor
  namespace: {{ .Release.Namespace }}
  labels:
    monitoring: istio-proxies
    release: prometheus-kubeaddons
spec:
  selector:
    matchExpressions:
      - {key: istio-prometheus-ignore, operator: DoesNotExist}
  namespaceSelector:
    any: true
  jobLabel: envoy-stats
  endpoints:
  - path: /stats/prometheus
    targetPort: 15090
    interval: {{ .Values.prometheus.scrapeInterval }}
    relabelings:
    - sourceLabels: [__meta_kubernetes_pod_container_port_name]
      action: keep
      regex: '.*-envoy-prom'
    - action: labelmap
      regex: "__meta_kubernetes_pod_label_(.+)"
    - sourceLabels: [__meta_kubernetes_namespace]
      action: replace
      targetLabel: namespace
    - sourceLabels: [__meta_kubernetes_pod_name]
      action: replace
      targetLabel: pod_name
