apiVersion: v1
name: serving
version: 0.3.1
kubeVersion: ">=1.15.0"
description: "Knative Serving"
sources:
- https://github.com/knative/serving
maintainers:
- name: chhsia0
- naem: gilbert88
appVersion: "v0.14.0"
