apiVersion: v2
name: serving
version: 1.15.2
kubeVersion: ">=1.24.0"
description: "Knative Serving"
sources:
  - https://github.com/knative/serving
maintainers:
  - name: adityajariwala
appVersion: "v1.17.0"
