{{- if .Values.karma.configMap.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: karma-configmap-cleanup
  labels:
{{ include "kommander-karma.labels" . | indent 4 }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: karma-configmap-cleanup
    spec:
      serviceAccountName: {{ .Values.kommanderServiceAccount }}
      containers:
        - name: kubectl
          image: bitnami/kubectl:1.16.2
          imagePullPolicy: IfNotPresent
          command:
            - /bin/sh
            - -c
            - kubectl delete configmap --ignore-not-found {{ .Values.kommanderKarmaConfigMap }}
      restartPolicy: OnFailure
{{- end }}
