apiVersion: v1
kind: Secret
metadata:
  name: {{ template "traefik-forward-auth.fullname" . }}
type: Opaque
data:
  clientSecret: {{ required "traefikForwardAuth.clientSecret is required" .Values.traefikForwardAuth.clientSecret.value | b64enc | quote }}
  secret: {{ required "traefikForwardAuth.secret is required" .Values.traefikForwardAuth.secret | b64enc | quote }}
---
apiVersion: v1
kind: Secret
metadata:
  name: ops-portal-credentials
data:
  # cGxhY2Vob2xkZXIK is "placeholder" and will be regenerated before container deployment
  # TODO: this should be reworked to not require the placeholder (see: DCOS-56555)
  username: cGxhY2Vob2xkZXIK
  password: cGxhY2Vob2xkZXIK
