enabled: false

image:
  repository: "quay.io/external_storage/local-volume-provisioner"
  tag: "v2.3.2"
  pullPolicy: "IfNotPresent"

storageclass:
  isDefault: true
  reclaimPolicy: Delete
  volumeBindingMode: WaitForFirstConsumer

priorityClassName: system-node-critical

tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
