# Default values for dex-controller.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
controller:
  replicas: 1
  manager:
    image: timaa2k/dex-controller:latest
    imagePullPolicy: Always #IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 30Mi
      requests:
        cpu: 100m
        memory: 20Mi
  proxy:
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.4.0
    imagePullPolicy: IfNotPresent
    resources: {}
