apiVersion: v1
name: grafana
# This chart is deprecated and moved to https://github.com/grafana/helm-charts
# For details including how to un-deprecate a chart see the PROCESSES.md file.
deprecated: true
version: 5.5.8
appVersion: 7.1.1
kubeVersion: "^1.8.0-0"
description: Lalala testing do not merge
home: https://grafana.net
icon: https://raw.githubusercontent.com/grafana/grafana/master/public/img/logo_transparent_400x.png
sources:
  - https://github.com/grafana/grafana
engine: gotpl
