image:
  registry: ghcr.io
  repository: mesosphere/dkp-container-images/objectstorage-controller
  tag: v0.2.2
  pullPolicy: IfNotPresent

extraArgs:
  v: 5

priorityClassName: system-cluster-critical

tolerations:
  - effect: NoSchedule
    operator: Exists
  - effect: NoExecute
    operator: Exists
  - key: CriticalAddonsOnly
    operator: Exists
