# Gateway component configuration
gateway:
  enabled: true
  name: istio-ingressgateway
  proxy:
    # "auto" means image is populated by mutating webhook at runtime
    image: auto
  priorityClassName: ""
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 2
  labels:
    istio: ingressgateway
