bearerproxy:
  port: 9091
  image:
    repository: "quay.io/joejulian/bearerproxy"
    tag: "latest"
    pullPolicy: "Always"
  resources: {}
  # requests:
  #   memory: "128Mi"
  #   cpu: "100m"
  # limits:
  #   memory: "256Mi"
  #   cpu: "200m"

landing:
  enabled: true
  resources: {}
  # requests:
  #   memory: "128Mi"
  #   cpu: "100m"
  # limits:
  #   memory: "256Mi"
  #   cpu: "200m"

# these secrets are created via hooks
secrets:
  create: true
  name: ops-portal-credentials
  image:
    repository: "mesosphere/kubeaddons-addon-initializer"
    tag: "v0.0.2"

opsportal:
  ingress:
    paths:
      # kubernetes-dashboard
      - backend:
          serviceName: bearerproxy
          servicePort: 9091
        path: /ops/portal/kubernetes
      # kibana
      - backend:
          serviceName: kibana-kubeaddons
          servicePort: 5601
        path: /ops/portal/kibana
      # grafana
      - backend:
          serviceName: prometheus-kubeaddons-grafana
          servicePort: 3000
        path: /ops/portal/grafana
      # prometheus
      - backend:
          serviceName: prometheus-kubeaddons-prom-prometheus
          servicePort: 9090
        path: /ops/portal/prometheus
      # alertmanager
      - backend:
          serviceName: prometheus-kubeaddons-prom-alertmanager
          servicePort: 9093
        path: /ops/portal/alertmanager
      # traefik
      - backend:
          serviceName: traefik-kubeaddons-dashboard
          servicePort: 80
        path: /ops/portal/traefik


###############################################################################
#  Konvoy UI
###############################################################################
kommander:
  image:
    repository: mesosphere/kommander
    tag: 1.60.0
    pullPolicy: IfNotPresent
  replicas: 1
  logoutRedirectPath: /ops/landing
  clusterPollingInterval: 3000
  clientPollingInterval: 3000

  # Mode must be either production|konvoy
  mode: konvoy

  displayName: Konvoy Cluster

  createObservableClusterCRD: true

  extraInitContainers:

  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "2000m"

  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 3
  livenessProbe:
    initialDelaySeconds: 15
    periodSeconds: 3

  ### This must match the serviceName set in the ingress backend below
  service:
    name: opsportal

  ingress:
    traefikFrontendRuleType: PathPrefixStrip
    path: /ops/portal/
    extraAnnotations:
      traefik.ingress.kubernetes.io/priority: "1"
      traefik.ingress.kubernetes.io/auth-type: forward
      traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kubeaddons.kubeaddons.svc.cluster.local:4181/
      traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
