landing:
  enabled: true
  resources: {}
  # requests:
  #   memory: "128Mi"
  #   cpu: "100m"
  # limits:
  #   memory: "256Mi"
  #   cpu: "200m"

# these secrets are created via hooks
secrets:
  create: true
  name: ops-portal-credentials
  image:
    repository: "mesosphere/kubeaddons-addon-initializer"
    tag: "v0.1.6"


# We need to override certain values from default kommander values here
kommander-ui:
  enabled: true
  image:
    repository: mesosphere/kommander
    tag: 1.192.0
    pullPolicy: IfNotPresent
  replicas: 1
  logoutRedirectPath: /ops/landing
  clusterPollingInterval: 3000

  # Mode must be either production|konvoy, konvoy forcing ui in "konvoy mode"
  mode: konvoy

  displayName: Konvoy Cluster

  ### This must match the serviceName set in the ingress backend below
  service:
    name: opsportal

  ingress:
    traefikFrontendRuleType: PathPrefixStrip
    path: /ops/portal/
    extraAnnotations:
      traefik.ingress.kubernetes.io/priority: "1"
      traefik.ingress.kubernetes.io/auth-type: forward
      traefik.ingress.kubernetes.io/auth-url: http://traefik-forward-auth-kubeaddons.kubeaddons.svc.cluster.local:4181/
      traefik.ingress.kubernetes.io/auth-response-headers: X-Forwarded-User
