# D2iQ Istio Istiod Chart Values

global:
  # Used by istiod templates as fallback when pilot.hub/tag not set
  hub: docker.io/istio
  tag: 1.23.6
  imagePullPolicy: IfNotPresent
  istioNamespace: istio-system

# Istiod component configuration
istiod:
  enabled: true
  priorityClassName: "dkp-critical-priority"
  pilot:
    replicaCount: 2

# Grafana dashboards
grafana:
  enabled: true

# Prometheus Operator ServiceMonitors
prometheus:
  enabled: true

prometheus-operator:
  serviceMonitor:
    labels: {}

# Security (certificate management)
security:
  enabled: true
  issuerName: kommander-ca
  image: docker.io/bitnamilegacy/kubectl
  tag: 1.29.2
