apiVersion: v1
name: traefik
version: 3.3.2
appVersion: 2.1.1
description: A Traefik based Kubernetes ingress controller
keywords:
  - traefik
  - ingress
home: https://traefik.io/
sources:
  - https://github.com/containous/traefik
  - https://github.com/containous/traefik-helm-chart
maintainers:
  - name: emilevauge
    email: emile@vauge.com
  - name: dtomcej
    email: daniel.tomcej@gmail.com
  - name: ldez
    email: ludovic@containo.us
engine: gotpl
icon: http://traefik.io/traefik.logo.png
