---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "kommander.fullname" . }}
  labels:
    app: {{ template "kommander.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ template "kommander.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "kommander.fullname" . }}
      namespace: {{ .Release.Namespace }}
    spec:
      serviceAccountName: {{ template "kommander.fullname" . }}
      imagePullSecrets:
        - name: dockerhub
      initContainers:
        {{- with .Values.extraInitContainers }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ template "kommander.fullname" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: "{{ .Values.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 4000
          resources:
            {{ with .Values.resources }}
            {{- toYaml . | nindent 12 }}
            {{- end }}
          readinessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: LOGOUT_REDIRECT_PATH
              value: {{ .Values.logoutRedirectPath }}
            - name: MODE
              value: {{ .Values.mode }}
