---
apiVersion: v1
kind: Namespace
metadata:
  name: kommander
spec:
  finalizers:
  - kubernetes
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kommander-deployment
  namespace: kommander
  labels:
    app: kommander
spec:
  replicas: {{ .Values.kommander.replicas }}
  selector:
    matchLabels:
      app: kommander
  template:
    metadata:
      labels:
        app: kommander
      namespace: kommander
    spec:
      serviceAccountName: admin-user-kommander
      imagePullSecrets:
        - name: dockerhub
      containers:
        - name: kommander
          image: "{{ .Values.kommander.image.repository }}:{{ .Values.kommander.image.tag }}"
          imagePullPolicy: "{{ .Values.kommander.image.pullPolicy }}"
          ports:
            - name: http
              containerPort: 4000
          resources:
            requests:
              memory: "128Mi"
              cpu: "1000m"
            limits:
              memory: "512Mi"
              cpu: "4000m"
          livenessProbe:
            httpGet:
              path: /health
              port: 4000
            initialDelaySeconds: 15
            periodSeconds: 3
