agent:
  namespaceOverride: ntnx-system
  name: konnector-agent
  port: 8080
  image:
    repository: docker.io/nutanix
    name: konnector-agent
    pullPolicy: IfNotPresent
    tag: "1.3.0"
    privateRegistry: false
    imageCredentials:
      dockerconfig: replace_base64_encoded_creds
  updateConfigInMin: 5
  updateMetricsInMin: 360
  config:
    registration:
      delete:
        force: false
    kubeconfig:
      delete:
        force: false

pc:
  port: 9440
  insecure: false  # set this to true if PC does not have https enabled
  endpoint: ""  # eg: ip or fqdn
  username: ""  # eg: admin or any other user with Kubernetes Infrastructure provision role
  password: ""
k8sClusterName: ""
k8sDistribution: "CAPX"  # eg: CAPX or NKE or OCP or EKSA or NKP
categoryMappings: ""  # "one or more comma separated key=value" eg: "key1=value1" or "key1=value1\,key2=value2"
createSecret: false  # set this to true if you want to create the secret with PC credentials. By default CAREN will create this during addon deployment
