{{- if .Values.federate.addons }}
---
apiVersion: types.kubefed.io/v1beta1
kind: FederatedAddon
metadata:
  name: {{ include "kommander-thanos.short-name-prefix" . }}-proxy
  namespace: {{ .Values.federate.systemNamespace.name }}
  labels:
{{ include "kommander-thanos.labels" . | indent 4 }}
spec:
  placement:
    clusterSelector:
      matchLabels: {}
      matchExpressions:
        - {key: kommander.mesosphere.io/connection-type, operator: NotIn, values: [unidirectional]}
  template:
    metadata:
      namespace: kubeaddons
      labels:
        kubeaddons.mesosphere.io/name: {{ include "kommander-thanos.short-name-prefix" . }}-proxy
    spec:
      namespace: {{ .Values.federate.systemNamespace.name }}
      chartReference:
        chart: mtls-proxy
        repo: {{ if .Values.global.federate.airgapped.enabled }}{{ .Values.global.federate.airgapped.chartRepo }}{{ else }}https://mesosphere.github.io/charts/stable{{ end }}
        version: 0.1.5
        values: |
          ---
          target: {{ required "thanos address must be set" .Values.thanosAddress }}
          certSecretName: {{ template "kommander-thanos.fullname" . }}-server-tls
          ingress:
            enabled: false
          service:
{{- if .Values.global.federate.airgapped.enabled }}
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-internal: "true"
{{- end }}
            type: LoadBalancer
            port: 443
          deployment:
            annotations:
              secret.reloader.stakater.com/reload: {{ template "kommander-thanos.fullname" . }}-server-tls
{{ end }}
