apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ template "nvidia-driver.fullname" . }}
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name: {{ template "nvidia-driver.fullname" . }}
  template:
    metadata:
      labels:
        name: {{ template "nvidia-driver.fullname" . }}
    spec:
{{- if .Values.tolerations }}
      tolerations:
{{- toYaml .Values.tolerations | nindent 8 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{- toYaml .Values.nodeSelector | nindent 8 }}
{{- end }}
{{- if .Values.initContainers }}
      initContainers:
{{- toYaml .Values.initContainers | nindent 8 }}
{{- end }}
      priorityClassName: {{ .Values.priorityClassName }}
      hostPID: true
      containers:
      - name: nvidia-driver
        command:
          - /usr/bin/wrapper.sh
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          privileged: true
{{- if .Values.resources }}
        resources:
{{- toYaml .Values.resources | nindent 12 }}
{{- end }}
        volumeMounts:
        - name: update-driver
          mountPath: /run/kernel/postinst.d
        - name: driver-path
          mountPropagation: Bidirectional
          mountPath: /run/nvidia
        - name: modules
          mountPath: /lib/modules
        - name: vault-repo
          mountPath: /etc/yum.repos.d/CentOS-Vault.repo
          subPath: CentOS-Vault.repo
        - name: wrapper-sh
          mountPath: /usr/local/bin/wrapper.sh
          subPath: wrapper.sh
      volumes:
      - name: update-driver
        hostPath:
          path: /etc/kernel/postinst.d
      - name: driver-path
        hostPath:
          path: /run/nvidia
      - name: modules
        hostPath:
          path: /lib/modules
      - name: vault-repo
        configMap:
          name: {{ template "nvidia-driver.fullname" . }}-centos7-vault-repo
      - name: wrapper-sh
        configMap:
          name: {{ template "nvidia-driver.fullname" . }}-wrapper-sh
