---
apiVersion: v1
appVersion: "latest"
description: Minimal forward authentication service that provides OIDC based login and authentication for the traefik reverse proxy
name: traefik-forward-auth
version: 0.2.1
keywords:
  - traefik-forward-auth
  - traefik
  - oauth
home: https://github.com/jongiddy/traefik-forward-auth
maintainers:
  - name: jongiddy
    email: jgiddy@mesosphere.com
