---
apiVersion: v1
appVersion: "3.0.2"
description: Minimal forward authentication service that provides OIDC based login and authentication for the traefik reverse proxy
name: traefik-forward-auth
version: 0.3.2
keywords:
  - traefik-forward-auth
  - traefik
  - oauth
home: https://github.com/mesosphere/traefik-forward-auth
maintainers:
  - name: jongiddy
    email: jgiddy@d2iq.com
  - name: jr0d
    email: jrodriguez@d2iq.com
